import SeoMeta from "../seo/SeoMeta";
import { FaHome } from "react-icons/fa";
import { Link } from "react-router-dom";

export default function CalculatorLayout({ title, subtitle, description, children,  content,
 }) {
  return (
    <div className="container py-4">
      <SeoMeta title={title} description={description} />


       <div className="mb-3">
        <Link
          to="/"
          className="d-inline-flex align-items-center text-decoration-none text-secondary"
        >
          <FaHome className="me-2" />
          <span>Home</span>
        </Link>
      </div>

      <h1 className="mb-2">{title}</h1>
      {subtitle && <h5 className="text-primary fw-semibold mb-3">{subtitle}</h5>}

      <h6>{description}</h6>

      <div className="card p-4 my-4 shadow-sm">
  {children}
</div>

{content?.howToUse && (
  <>
    <h4>How to Use This Calculator</h4>
    <ol>
      {content.howToUse.map((step, i) => (
        <li key={i}>{step}</li>
      ))}
    </ol>
  </>
)}

{content?.features && (
  <>
    <h4>Features of This Online Calculator</h4>
    <ul>
      {content.features.map((feature, i) => (
        <li key={i}>{feature}</li>
      ))}
    </ul>
  </>
)}

{content?.whyUse && (
  <>
    <h4>Why Use This Calculator?</h4>
    <p>{content.whyUse}</p>
  </>
)}

{content?.notes && (
  <>
    <h4>Important Notes</h4>
    <ul>
      {content.notes.map((note, i) => (
        <li key={i}>{note}</li>
      ))}
    </ul>
  </>

)}
<h4>Disclaimer</h4>
<p>
This calculator is provided for informational and educational purposes only. While we strive to ensure accuracy, the results generated by this tool are not guaranteed and should not be considered as professional, financial, legal, medical, or technical advice. Actual results may vary depending on input values, assumptions, and calculation methods. Users are advised to verify critical results independently and consult qualified professionals when making important decisions.
</p>

    </div>
  );
}
