import SeoMeta from "../seo/SeoMeta";
import { FaHome } from "react-icons/fa";
import { Link } from "react-router-dom";

export default function CalculatorLayout({ title, description, children,  content,  relatedCalculators
 }) {
  return (
    <div className="container py-4">
      <SeoMeta title={title} description={description} />


       <div className="mb-3">
        <Link
          to="/"
          className="d-inline-flex align-items-center text-decoration-none text-secondary"
        >
          <FaHome className="me-2" />
          <span>Home</span>
        </Link>
      </div>

      <h1 className="mb-2">{title}</h1>
      

      <h5>{description}</h5>

      <div className="card p-4 my-4 shadow-sm calculator-box">
  {children}
</div>
{/* Related Calculators */}
{relatedCalculators?.length > 0 && (
  <div className="related-calculators mb-5">
    <h2 className="related-title">Related Calculators</h2>

    <div className="related-list">
      {relatedCalculators.map((calc, i) => (
        <Link
          key={i}
          to={`/${calc.slug}`}
          className="related-item"
        >
          {calc.name}
        </Link>
      ))}
    </div>
  </div>
)}




{content?.formula && (
  <section className="content-section">
    <h2 className="section-title">How the Calculation Works</h2>
    <div
      className="section-body"
      dangerouslySetInnerHTML={{ __html: content.formula }}
    />
  </section>
)}

{content?.howToUse && (
  <section className="content-section">
    <h2 className="section-title">How to Use This Calculator</h2>
    <ol className="section-list">
      {content.howToUse.map((step, i) => (
        <li key={i}>{step}</li>
      ))}
    </ol>
  </section>
)}

{content?.features && (
  <section className="content-section">
    <h2 className="section-title">Features of This Online Calculator</h2>
    <ul className="section-list">
      {content.features.map((feature, i) => (
        <li key={i}>{feature}</li>
      ))}
    </ul>
  </section>
)}

{content?.whyUse && (
  <section className="content-section">
    <h2 className="section-title">Why Use This Calculator?</h2>
    <p className="section-text">{content.whyUse}</p>
  </section>
)}

{content?.notes && (
  <section className="content-section">
    <h2 className="section-title">Important Notes</h2>
    <ul className="section-list">
      {content.notes.map((note, i) => (
        <li key={i}>{note}</li>
      ))}
    </ul>
  </section>
)}

<section className="content-section disclaimer">
  <h2 className="section-title">Disclaimer</h2>
  <h6 className="section-text">
    This calculator is provided for informational and educational purposes only. While we strive to ensure accuracy, the results generated by this tool are not guaranteed and should not be considered as professional, financial, legal, medical, or technical advice. Actual results may vary depending on input values, assumptions, and calculation methods. Users are advised to verify critical results independently and consult qualified professionals when making important decisions.
  </h6>
</section>

    </div>
  );
}
